services:
  - type: web
    name: telegram-bot
    plan: free
    runtime: python
    buildCommand: pip install -r simple_bot/requirements.txt
    startCommand: python simple_bot/bot_webhook.py
    envVars:
      - key: PORT
        value: 8443
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: BOT_TOKEN
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: WEBHOOK_URL
        sync: false
