services:
  - type: web
    name: telegram-bot
    plan: free
    runtime: python
    buildCommand: pip install -r simple_bot/requirements.txt
    startCommand: python simple_bot/bot_webhook.py
    envVars:
      - key: PORT
        value: 8443
      - key: PYTHON_VERSION
        value: 3.12.1
      - fromGroup: telegram-bot-secrets
